{% set name = "psdtags" %}
{% set version = "2025.5.10" %}
{% set sha256 = "a2360d7c1df5246ae64cf755541f6144001f4e4c3ae2eef04c2af2d8228ab5c1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - psdtags = psdtags.psdtags:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - psdtags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com/
  summary: Read and write layered TIFF ImageSourceData and ImageResources tags
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Psdtags is a Python library to read and write the Adobe Photoshop(r) specific ImageResources (#34377) and ImageSourceData (#37724) TIFF tags, which contain image resource blocks, layer and mask information found in a typical layered TIFF file created by Photoshop.
  dev_url: https://github.com/cgohlke/psdtags

extra:
  recipe-maintainers:
    - cgohlke
